# Generated by Django 4.2.1 on 2023-06-02 15:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ticket", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="validity",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 6, 9, 15, 53, 48, 114893)
            ),
        ),
    ]
