# Generated by Django 4.2.1 on 2023-06-02 16:35

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ticket", "0002_alter_ticket_validity"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="user",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="ticket",
            name="validity",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 6, 9, 16, 35, 4, 566218)
            ),
        ),
    ]
