# Generated by Django 4.2.1 on 2023-06-02 16:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ticket", "0003_ticket_user_alter_ticket_validity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="validity",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 6, 9, 16, 39, 19, 1551)
            ),
        ),
    ]
